### ISSUE TITLE
Fix username not shown in dashboard

### ISSUE THREAD

**Issue by thedipankarroy** [thedipankarroy/ubercoders#3]
<img width="606" alt="Screenshot 2024-12-26 at 12 49 51" src="https://github.com/user-attachments/assets/753fd687-b458-48b6-86ce-64773d6e2e68" />

**Comment by jeyasimma** [comment]
Could you assign it to me ? I will try to solve it...

**Comment by thedipankarroy** [comment]
Sure.

**Comment by jeyasimma** [comment]
I am not able to view the exact page to track the user problem. when I check that dashboard.html it shows User.

**Comment by thedipankarroy** [comment]
Yes it is in the dashboard.html file.

Click on signup on the landing page then signup or login depending on if you have created your account before.

<img width="720" alt="Screenshot 2024-12-30 at 09 02 25" src="https://github.com/user-attachments/assets/3a0e3400-5c5e-4de7-944e-b069b2fa536c" />

These are the errors shown in console after logging in.

**Comment by jeyasimma** [comment]
ooh okay, It is an Module Error . I check it and correct it.

**Comment by jeyasimma** [comment]
Error problem is solved but username is not shown because of fetching user data probem. 
![Screenshot from 2025-01-01 18-26-50](https://github.com/user-attachments/assets/7dcbdc1c-ad90-4ab5-ae3f-d061d4393cb2)

**Comment by thedipankarroy** [comment]
Thanks @jeyasimma, I will look into why the server isn't responding correctly.

**Comment by Deepanshu902** [comment]
Hey is this fixed or is there still a problem from server side?

**Comment by thedipankarroy** [comment]
@Deepanshu902 As @jeyasimma Hasn't made any pull requests regarding the solution it is still the same, You could also try solving the issue and make a pull request.

**Comment by jeyasimma** [comment]
> Hey is this fixed or is there still a problem from server side?
you try

**Comment by thedipankarroy** [comment]
Besides the server which I am working on, everything is still same, @jeyasimma you could make a pull request with your previous solution.

**Comment by jeyasimma** [comment]
I am facing an issue where the /api/user endpoint takes too long to respond. This delay is affecting the user experience, as the dashboard elements dependent on this data are not loading instantly.  Now, I just solve that console errors only

![Image](https://github.com/user-attachments/assets/498b8afd-7db4-417e-a6d2-6d5ce4f620b6)
I can't solve the user name shown problem and it takes some API and fetching problems
